spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ideal920/tensquare_config.git
          search-paths: #搜索路径 码云中配置文件的文件夹
          username: ideal920  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: WWW_1314_com
  rabbitmq:
    host: 192.168.200.146
management: #暴露消息总线地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 12000